# Generated by Django 2.0 on 2018-04-04 23:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 4, 23, 50, 38, 630610, tzinfo=utc)),
        ),
    ]
