# Generated by Django 2.0 on 2018-04-05 00:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20180405_0807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='is_delete',
            new_name='is_deleted',
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 5, 0, 16, 17, 172610, tzinfo=utc)),
        ),
    ]
